#!/bin/bash

# Script to NUCLEAR disable verbose boot text (quiet splash, hidden menu, no timeout)
# It modifies /etc/default/grub and runs update-grub

set -e

# Auto-elevate to root if not already
if [[ $EUID -ne 0 ]]; then
   echo "This script requires root privileges. Elevating..."
   exec sudo "$0" "$@"
fi

GRUB_FILE="/etc/default/grub"
BACKUP_FILE="${GRUB_FILE}.bak.$(date +%F_%T)"

echo "Backing up $GRUB_FILE to $BACKUP_FILE..."
cp "$GRUB_FILE" "$BACKUP_FILE"

# Only proceed if backup succeeded
if [[ -f "$BACKUP_FILE" ]]; then
    echo "Backup created successfully."
else
    echo "Failed to create backup. Exiting."
    exit 1
fi

echo "Overwriting $GRUB_FILE with NUCLEAR silent settings..."

# We use tee to write the file with root privileges (already root here, but good practice)
cat <<EOF > "$GRUB_FILE"
# NUCLEAR SILENT GRUB CONFIGURATION
# Generated by disable_grub_text.sh

# 1. Hide the menu completely
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_TIMEOUT_STYLE=hidden

# 2. Prevent fallback timeout on failed boot (force immediate boot always)
GRUB_RECORDFAIL_TIMEOUT=0

# 3. Remove distributor text (removes "Welcome to GRUB" etc)
GRUB_DISTRIBUTOR=""

# 4. Aggressive kernel silence
# quiet: less text
# splash: show logo (if theme exists)
# loglevel=0: disable most kernel messages
# rd.systemd.show_status=false: hide systemd 'OK' messages
# rd.udev.log_level=3: hide udev messages
# vt.global_cursor_default=0: hide the blinking underscore cursor
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash loglevel=0 rd.systemd.show_status=false rd.udev.log_level=3 vt.global_cursor_default=0"

GRUB_CMDLINE_LINUX=""

# 5. Disable OS Prober (speeds up update-grub, prevents other OS menu entries)
GRUB_DISABLE_OS_PROBER=true

# Standard options
#GRUB_TERMINAL=console
#GRUB_GFXMODE=640x480
#GRUB_DISABLE_LINUX_UUID=true
#GRUB_DISABLE_RECOVERY="true"
#GRUB_INIT_TUNE="480 440 1"
EOF

echo "Configuration written."
echo "Updating GRUB..."
update-grub

echo "Done! The system should be completely silent on next reboot."
echo "WARNING: To access recovery menu, you will need to hold SHIFT or press ESC rapidly during BIOS post."
